spring:
  application:
    name: GariZetu

  datasource:
    url: "jdbc:postgresql://localhost:5432/garizetu"
    username: cfreak97
    password: "tarak#23h!"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 25MB

file:
  upload:
    directory: ${FILE_UPLOAD_DIR:${user.home}/garizetu/uploads}

cloudinary:
  cloud-name: "dicnb9x6z"
  api-key: "633256643316292"
  api-secret: "17vAylBr1gjWcUDK6JMVn67f1gQ"

jwt:
  secret: "garizetu-super-secret-key-change-this-in-production-minimum-32-characters-required"
  expiration: 86400000
