spring:
  application:
    name: GariZetu

  datasource:
    url: "jdbc:postgresql://localhost:5432/garizetu"
    username: cfreak97
    password: "tarak#23h!"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
    directory: /home/cfreak97/Desktop/GariZetu_Project/uploads


cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

