spring:
  application:
    name: GariZetu

  datasource:
    url: "jdbc:postgresql://localhost:5432/garizetu"
    username: cfreak97
    password: "tarak#23h!"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql


cloudinary:
  cloud-name: "dicnb9x6z"
  api-key: "633256643316292"
  api-secret: "17vAylBr1gjWcUDK6JMVn67f1gQ"
